server:
  port: ${PORT} # Use the PORT environment variable provided by Heroku
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME} # Use the DATABASE_URL environment variable provided by Heroku
    username: ${PROD_DB_USERNAME} # Use environment variables for sensitive information
    password: ${PROD_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # Change to update or validate for production, create-drop is not suitable
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
      show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: dzrekepokunathan123@gmail.com
    password: ${GMAIL_PASSWORD} # Use environment variables for sensitive information
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
